"""create_therapist_models

Revision ID: d2554c1ca879
Revises: 9de13c455fa8
Create Date: 2026-09-24 19:53:59.379076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2554c1ca879'
down_revision: Union[str, Sequence[str], None] = '9de13c455fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('working_days', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('break_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('break_end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_name'), 'therapist', ['name'], unique=False)
    op.create_table('scheduleoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('custom_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('break_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('break_end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduleoverride_therapist_id'), 'scheduleoverride', ['therapist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduleoverride_therapist_id'), table_name='scheduleoverride')
    op.drop_table('scheduleoverride')
    op.drop_index(op.f('ix_therapist_name'), table_name='therapist')
    op.drop_table('therapist')
    # ### end Alembic commands ###

