"""create_invoice_table

Revision ID: 362e07aefa17
Revises: 5c2ff5da98ad
Create Date: 2026-09-24 20:18:09.476227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '362e07aefa17'
down_revision: Union[str, Sequence[str], None] = '5c2ff5da98ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_or_package', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoice_patient_id'), 'invoice', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_patient_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###

